version: 2.1
orbs:
  codecov: codecov/codecov@dev:alpha
  node: circleci/node@5
  orb-tools: circleci/orb-tools@11
  python: circleci/python@2
  win: circleci/windows@4

filters: &filters
  tags:
    only: /.*/

executors:
  python:
    docker:
      - image: cimg/python:3.10
  node:
    docker:
      - image: cimg/node:current

jobs:
  test-backend:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: |
          coverage run -m unittest discover
      - persist_to_workspace:
          root: .
          paths:
            - .coverage
  test-frontend:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - coverage/coverage-final.json
  test-alpine:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          apk add coreutils curl git gnupg
          mkdir ~/.gnupg
          touch ~/.gnupg/trustedkeys.gpg
      - codecov/upload:
          environment:
            CODECOV_FLAGS: backend,alpine
      - codecov/upload:
          file: coverage/coverage-final.json
          xtra_args: -v -Z
          environment:
            CODECOV_FLAGS: frontend,alpine
      - codecov/upload:
          file: coverage/coverage-final.json
          version: v0.1.0_8880
          environment:
            CODECOV_FLAGS: version,alpine
  test-linux:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - codecov/upload:
          environment:
            CODECOV_FLAGS: backend,linux
      - codecov/upload:
          file: coverage/coverage-final.json
          xtra_args: -v -Z
          environment:
            CODECOV_FLAGS: frontend,linux
      - codecov/upload:
          file: coverage/coverage-final.json
          version: v0.1.0_8880
          environment:
            CODECOV_FLAGS: version,linux
  test-macos:
    macos:
      xcode: 14.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - codecov/upload:
          environment:
            CODECOV_FLAGS: backend,macos
      - codecov/upload:
          file: coverage/coverage-final.json
          environemnt:
            CODECOV_FLAGS: frontend,macos
          xtra_args: -v -Z
      - codecov/upload:
          file: coverage/coverage-final.json
          environemnt:
            CODECOV_FLAGS: version,macos
          version: v0.1.0_8880
  test-windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - attach_workspace:
          at: .
      - codecov/upload:
          environemnt:
            CODECOV_FLAGS: backend,windows
      - codecov/upload:
          file: coverage/coverage-final.json
          environemnt:
            CODECOV_FLAGS: frontend,windows
          xtra_args: -v -Z
      - codecov/upload:
          file: coverage/coverage-final.json
          environemnt:
            CODECOV_FLAGS: version,windows
          version: v0.1.0_8880

workflows:
  integration-tests_deploy:
    jobs:
      - test-backend:
          filters: *filters
      - test-frontend:
          filters: *filters
      - test-alpine:
          filters: *filters
          requires: [test-backend, test-frontend]

      - test-linux:
          filters: *filters
          requires: [test-backend, test-frontend]

      - test-macos:
          filters: *filters
          requires: [test-backend, test-frontend]

      - test-windows:
          filters: *filters
          requires: [test-backend, test-frontend]

      - orb-tools/pack:
          filters: *filters
          requires: [test-alpine, test-linux, test-macos, test-windows]

      - orb-tools/publish:
          circleci-token: ORB_PUBLISH_TOKEN
          context: Codecov Orb Context
          enable-pr-comment: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
          orb-name: codecov/codecov
          pub-type: production
          requires:
            - orb-tools/pack
          vcs-type: github
